### ISSUE TITLE
Able App  Version 4

### ISSUE THREAD

**Issue by ekeane28** [able-to-include/accessibility-layer#2]
The app disables itself when I leave my phone for a minute or so (and you get a black home screen/stand by mode?). When I open Facebook there’s no more service strip and the app is disabled when I check accessibility settings.

**Comment by asi-soft** [comment]
@ekeane28,
Is this issue related to the Accessibility Layer or maybe to the [ABLE Social Media Accessibility App](https://github.com/able-to-include/ABLE-Social-Media-Accessibility-App)?
