### ISSUE TITLE
Able App Version 4

### ISSUE THREAD

**Issue by ekeane28** [able-to-include/accessibility-layer#3]
For a lot of sentences I get the message: unable to get pictos. Problem parsing pictos – and sometimes connectivity issue

**Comment by ekeane28** [comment]
The picto service does not seem to be able to handle emojis

**Comment by asi-soft** [comment]
@ekeane28,
Is this issue related to the Accessibility Layer or maybe to the [ABLE Social Media Accessibility App](https://github.com/able-to-include/ABLE-Social-Media-Accessibility-App)?
